<?php

namespace YM\TestBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MusicianController__JMSInjector
{
    public static function inject($container) {
        $instance = new \YM\TestBundle\Controller\MusicianController();
        return $instance;
    }
}
